theme = "bento"
languageCode = "en-us"
baseurl = "https://bento-hugo-theme.netlify.app/"
title = "Bento"

author = "Leonardo Faria"
copyright = "MIT"

# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "vs"

googleAnalytics = "UA-157386-36"
disqusShortname = "bento-hugo-theme"

[taxonomies]
category = "categories"
tag = "tags"

[markup.highlight]
  style = "github"
[markup.goldmark.renderer]
  unsafe = true

[params]
  name = "Bento"
  intro = true
  headline = "This is a headline"
  description = "A minimalist theme for Hugo, build with Tailwind CSS."

  copyright = "Copyright © 2020 Someone"

  # favicon = "favicon.ico" # TODO: add support
  cover = "images/vancouver.jpg"
  ogImage = "images/og_image.jpg"

  github = "XXXX"
  twitter = "XXXX"
  linkedin = "https://linkedin.com/in/XXXX"
  email = "email@xxxx.com"


  # logo = "images/logo.png" # TODO: add support
  avatar = "images/avatar.jpg"

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Source code"
    url = "https://github.com/leonardofaria/bento"
    weight = 1
